import { NextRequest, NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';
import { renderSchemaContext, renderFilingTemplateContext } from '@/data/schemas';
import { checkAiGate } from '@/lib/ai-gate';

/**
 * POST /api/workflow/apply
 *
 * Two modes:
 *   dryRun: true  → Extract patches from analysis, validate, return diffs. NO writes.
 *   dryRun: false → Apply pre-validated patches from the preview step. Writes files.
 *
 * Merge-only contract — enforced at every level:
 * - INSERT new entries (before anchor)
 * - APPEND new content (after anchor)
 * - UPDATE specific values (old → new, anchor-constrained)
 * - NEVER delete lines, entries, or files
 *
 * Safety guarantees:
 * - Path traversal blocked (resolve + prefix check)
 * - Atomic writes (tmp + rename)
 * - Backup before write (.bak)
 * - Anchor uniqueness enforced
 * - Update: oldValue must be near anchor, appear exactly once
 * - Character-count guard: update content must be >= 50% of old length
 * - Code injection blocked (import/require/exec/eval)
 * - Idempotency: skip if content already present
 * - File line-count can never decrease
 *
 * BARREL EXPORT RULE (enforced by pre-write gate, not this route):
 * When patches introduce new exported symbols in data files, the caller
 * must also include a patch to the ticker's barrel (index.ts) to re-export
 * the new symbol. Orphaned exports are invisible to the UI.
 * Validation: bash scripts/check-barrel-exports.sh
 */

interface PatchOp {
  file: string;
  action: 'insert' | 'append' | 'update';
  anchor: string;
  content: string;
  oldValue?: string;
}

interface PatchPreviewItem {
  file: string;
  action: string;
  valid: boolean;
  detail: string;
  diff: string;       // unified diff preview
  linesAdded: number;
  autoGenerated?: boolean;  // true if cross-ref was auto-generated (not from AI)
}

interface PatchResult {
  file: string;
  action: string;
  success: boolean;
  detail: string;
}

const DATA_DIR = path.resolve(process.cwd(), 'src', 'data');
const ALLOWED_PREFIXES = ['asts/', 'bmnr/', 'crcl/'];
const TICKER_PATTERN = /^[a-z]{2,10}$/;
const MAX_ANALYSIS_LENGTH = 50_000;
const MAX_PATCH_CONTENT_LENGTH = 5_000;
const MAX_PATCH_COUNT = 20;
const MAX_BACKUPS_PER_FILE = 3;
const DANGEROUS_PATTERN = /\b(import\s|require\s*\(|exec\s*\(|eval\s*\(|process\.|child_process|Function\s*\()\b/;

// ─── Date normalizer (display date → ISO) ───────────────────────────────────

function normalizeDate(dateStr: string): string {
  if (/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) return dateStr;
  const rangeMatch = dateStr.match(/^(\w+ \d+)-\d+, (\d{4})$/);
  if (rangeMatch) {
    const d = new Date(`${rangeMatch[1]}, ${rangeMatch[2]}`);
    if (!isNaN(d.getTime())) return d.toISOString().slice(0, 10);
  }
  const d = new Date(dateStr);
  if (!isNaN(d.getTime())) return d.toISOString().slice(0, 10);
  return dateStr;
}

// ─── Source name mapping (filename → cross-ref source label) ────────────────

const FILE_SOURCE_MAP: Record<string, string> = {
  'capital.ts': 'capital',
  'financials.ts': 'financials',
  'quarterly-metrics.ts': 'financials',
  'timeline.ts': 'timeline',
  'catalysts.ts': 'catalysts',
  'company.ts': 'company',
  'partners.ts': 'partners',
  'ethereum-adoption.ts': 'ethereum',
};

// ─── Extract a one-line summary from patch content ──────────────────────────

function summarizePatchContent(content: string): string {
  // Try to find a description/event/title field
  const fieldMatch = content.match(/(?:description|event|title|summary):\s*['"]([^'"]{10,150})['"]/);
  if (fieldMatch) return fieldMatch[1];

  // Try to find a data field (common in timeline entries)
  const dataMatch = content.match(/data:\s*['"]([^'"]{10,150})['"]/);
  if (dataMatch) return dataMatch[1];

  // Fall back to cleaning up raw content
  return content
    .replace(/^\s+/gm, '')
    .replace(/[{}[\],]/g, ' ')
    .replace(/\w+:\s*/g, '')       // strip field names
    .replace(/['"`]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 120) || 'Data updated';
}

// ─── Auto-generate missing cross-ref patches ────────────────────────────────

async function ensureCrossRefPatches(patches: PatchOp[], ticker: string): Promise<{ patches: PatchOp[]; autoGenerated: number }> {
  const tickerLower = ticker.toLowerCase();
  const tickerUpper = ticker.toUpperCase();
  const secFilingsFile = `${tickerLower}/sec-filings.ts`;

  // Find SEC filing insert patches (new filing entries being added)
  const filingPatches = patches.filter(p =>
    p.file === secFilingsFile &&
    p.action === 'insert' &&
    /type:\s*['"]/.test(p.content) &&
    /date:\s*['"]/.test(p.content)
  );

  if (filingPatches.length === 0) return { patches, autoGenerated: 0 };

  // Read the actual file to find FILING_CROSS_REFS anchor
  const filePath = path.resolve(DATA_DIR, secFilingsFile);
  let fileContent: string;
  try {
    fileContent = await fs.readFile(filePath, 'utf-8');
  } catch {
    return { patches, autoGenerated: 0 };
  }

  // Find the FILING_CROSS_REFS export declaration — must exist
  const crossRefPattern = new RegExp(`${tickerUpper}_FILING_CROSS_REFS|FILING_CROSS_REFS`);
  const crossRefMatch = fileContent.match(crossRefPattern);
  if (!crossRefMatch) return { patches, autoGenerated: 0 };

  // Find the exact declaration line to use as anchor
  const declLineMatch = fileContent.match(
    new RegExp(`^export const \\w+FILING_CROSS_REFS[^=]*= \\{`, 'm')
  );
  if (!declLineMatch) return { patches, autoGenerated: 0 };
  const crossRefAnchor = declLineMatch[0];

  const additionalPatches: PatchOp[] = [];

  for (const fp of filingPatches) {
    // Extract type and date from the filing entry
    const typeMatch = fp.content.match(/type:\s*['"]([^'"]+)['"]/);
    const dateMatch = fp.content.match(/date:\s*['"]([^'"]+)['"]/);
    if (!typeMatch || !dateMatch) continue;

    const formType = typeMatch[1];
    const filingDate = dateMatch[1];
    const isoDate = normalizeDate(filingDate);
    const crossRefKey = `${formType}|${isoDate}`;

    // Check if any existing patch already targets this cross-ref key
    const hasCrossRef = patches.some(p =>
      p.content.includes(`'${crossRefKey}'`) || p.content.includes(`"${crossRefKey}"`)
    );
    if (hasCrossRef) continue;

    // Also check if cross-ref already exists in the file
    if (fileContent.includes(`'${crossRefKey}'`) || fileContent.includes(`"${crossRefKey}"`)) continue;

    // Build cross-ref entries from sibling patches targeting other data files
    const crossRefEntries: { source: string; data: string }[] = [];

    for (const p of patches) {
      if (p.file === secFilingsFile) continue;
      const fileName = p.file.split('/').pop() || '';
      const source = FILE_SOURCE_MAP[fileName];
      if (!source) continue;

      // Don't duplicate sources
      if (crossRefEntries.some(e => e.source === source)) continue;

      const summary = summarizePatchContent(p.content);
      crossRefEntries.push({ source, data: summary });
    }

    // If no sibling patches, add a minimal entry
    if (crossRefEntries.length === 0) {
      const descMatch = fp.content.match(/description:\s*['"]([^'"]+)['"]/);
      crossRefEntries.push({
        source: 'sec-filings',
        data: descMatch ? descMatch[1] : `${formType} filed ${filingDate}`,
      });
    }

    // Build cross-ref patch content
    const entriesStr = crossRefEntries
      .map(e => `    { source: '${e.source}', data: "${e.data.replace(/"/g, '\\"')}" },`)
      .join('\n');

    const crossRefContent = `  '${crossRefKey}': [\n${entriesStr}\n  ],`;

    additionalPatches.push({
      file: secFilingsFile,
      action: 'append',
      anchor: crossRefAnchor,
      content: crossRefContent,
    });
  }

  return {
    patches: [...patches, ...additionalPatches],
    autoGenerated: additionalPatches.length,
  };
}

// ─── Path safety ────────────────────────────────────────────────────────────

function resolveAndValidate(filePath: string): { valid: boolean; fullPath: string; detail: string } {
  const normalized = filePath.replace(/\\/g, '/');
  if (!ALLOWED_PREFIXES.some(p => normalized.startsWith(p)) || !normalized.endsWith('.ts')) {
    return { valid: false, fullPath: '', detail: `Blocked: ${filePath} not in allowed paths` };
  }
  const fullPath = path.resolve(DATA_DIR, filePath);
  if (!fullPath.startsWith(DATA_DIR + path.sep)) {
    return { valid: false, fullPath: '', detail: `Path traversal blocked: ${filePath}` };
  }
  return { valid: true, fullPath, detail: '' };
}

// ─── Simple diff generator ──────────────────────────────────────────────────

function generateDiff(original: string, modified: string, filePath: string): string {
  const oldLines = original.split('\n');
  const newLines = modified.split('\n');
  const diffLines: string[] = [`--- a/${filePath}`, `+++ b/${filePath}`];

  // Find ranges that changed — simple approach: walk both arrays
  let i = 0;
  let j = 0;
  while (i < oldLines.length || j < newLines.length) {
    if (i < oldLines.length && j < newLines.length && oldLines[i] === newLines[j]) {
      i++;
      j++;
      continue;
    }
    // Found a difference — collect context
    const contextStart = Math.max(0, i - 2);
    // Find how far the difference extends
    let iEnd = i;
    let jEnd = j;
    // Advance until lines match again
    while (iEnd < oldLines.length || jEnd < newLines.length) {
      if (iEnd < oldLines.length && jEnd < newLines.length && oldLines[iEnd] === newLines[jEnd]) {
        // Check if next few lines also match (to avoid false re-sync)
        let matchLen = 0;
        while (iEnd + matchLen < oldLines.length && jEnd + matchLen < newLines.length && oldLines[iEnd + matchLen] === newLines[jEnd + matchLen] && matchLen < 3) matchLen++;
        if (matchLen >= 2) break;
      }
      if (iEnd < oldLines.length && !newLines.includes(oldLines[iEnd])) { iEnd++; continue; }
      if (jEnd < newLines.length && !oldLines.includes(newLines[jEnd])) { jEnd++; continue; }
      iEnd++;
      jEnd++;
    }
    const contextEnd = Math.min(oldLines.length, iEnd + 2);
    const newContextEnd = Math.min(newLines.length, jEnd + 2);

    diffLines.push(`@@ -${contextStart + 1},${contextEnd - contextStart} +${Math.max(0, j - 2) + 1},${newContextEnd - Math.max(0, j - 2)} @@`);
    for (let c = contextStart; c < i; c++) diffLines.push(` ${oldLines[c]}`);
    for (let r = i; r < iEnd; r++) diffLines.push(`-${oldLines[r]}`);
    for (let a = j; a < jEnd; a++) diffLines.push(`+${newLines[a]}`);
    for (let c = iEnd; c < contextEnd; c++) diffLines.push(` ${oldLines[c]}`);

    i = contextEnd;
    j = newContextEnd;
  }

  return diffLines.join('\n');
}

// ─── Patch validation (no writes) ───────────────────────────────────────────

async function validatePatch(patch: PatchOp): Promise<PatchPreviewItem> {
  const base = { file: patch.file, action: patch.action };

  // Path check
  const pathCheck = resolveAndValidate(patch.file);
  if (!pathCheck.valid) {
    return { ...base, valid: false, detail: pathCheck.detail, diff: '', linesAdded: 0 };
  }

  // Content size limit
  if (patch.content.length > MAX_PATCH_CONTENT_LENGTH) {
    return { ...base, valid: false, detail: `Content too large: ${patch.content.length} chars (max ${MAX_PATCH_CONTENT_LENGTH})`, diff: '', linesAdded: 0 };
  }

  // Code injection check
  if (DANGEROUS_PATTERN.test(patch.content)) {
    return { ...base, valid: false, detail: 'Blocked: patch content contains dangerous code patterns', diff: '', linesAdded: 0 };
  }

  // Read file
  let content: string;
  try {
    content = await fs.readFile(pathCheck.fullPath, 'utf-8');
  } catch {
    return { ...base, valid: false, detail: `File not found: ${patch.file}`, diff: '', linesAdded: 0 };
  }

  // Anchor check — must exist and be unique
  const anchorIdx = content.indexOf(patch.anchor);
  if (anchorIdx === -1) {
    return { ...base, valid: false, detail: `Anchor not found: "${patch.anchor.slice(0, 80)}..."`, diff: '', linesAdded: 0 };
  }
  if (content.indexOf(patch.anchor, anchorIdx + 1) !== -1) {
    return { ...base, valid: false, detail: `Ambiguous anchor (appears multiple times): "${patch.anchor.slice(0, 60)}..."`, diff: '', linesAdded: 0 };
  }

  // Idempotency check for insert/append
  if ((patch.action === 'insert' || patch.action === 'append') && content.includes(patch.content.trim())) {
    return { ...base, valid: false, detail: 'Already present in file (duplicate)', diff: '', linesAdded: 0 };
  }

  // Compute preview
  let newContent: string;

  switch (patch.action) {
    case 'insert': {
      const lineStart = content.lastIndexOf('\n', anchorIdx);
      const insertAt = lineStart === -1 ? 0 : lineStart + 1;
      newContent = content.slice(0, insertAt) + patch.content + '\n' + content.slice(insertAt);
      break;
    }

    case 'append': {
      const lineEnd = content.indexOf('\n', anchorIdx);
      const insertAt = lineEnd === -1 ? content.length : lineEnd + 1;
      newContent = content.slice(0, insertAt) + patch.content + '\n' + content.slice(insertAt);
      break;
    }

    case 'update': {
      if (!patch.oldValue) {
        return { ...base, valid: false, detail: 'Update requires oldValue', diff: '', linesAdded: 0 };
      }

      // oldValue must appear exactly once in file
      const occurrences = content.split(patch.oldValue).length - 1;
      if (occurrences === 0) {
        return { ...base, valid: false, detail: `Old value not found: "${patch.oldValue.slice(0, 80)}..."`, diff: '', linesAdded: 0 };
      }
      if (occurrences > 1) {
        return { ...base, valid: false, detail: `Old value appears ${occurrences} times — ambiguous. Use a longer/more unique oldValue.`, diff: '', linesAdded: 0 };
      }

      // oldValue must be near the anchor (within ±2000 chars)
      const oldIdx = content.indexOf(patch.oldValue);
      if (Math.abs(oldIdx - anchorIdx) > 2000) {
        return { ...base, valid: false, detail: `Old value is ${Math.abs(oldIdx - anchorIdx)} chars from anchor — too far (max 2000)`, diff: '', linesAdded: 0 };
      }

      // Character-count guard: new content must be >= 50% of old
      if (patch.content.length < patch.oldValue.length * 0.5) {
        return { ...base, valid: false, detail: `Suspicious shrink: replacing ${patch.oldValue.length} chars with ${patch.content.length} chars (<50%)`, diff: '', linesAdded: 0 };
      }

      // Line-count guard
      const oldLines = patch.oldValue.split('\n').length;
      const newLines = patch.content.split('\n').length;
      if (newLines < oldLines) {
        return { ...base, valid: false, detail: `Would remove ${oldLines - newLines} lines`, diff: '', linesAdded: 0 };
      }

      newContent = content.slice(0, oldIdx) + patch.content + content.slice(oldIdx + patch.oldValue.length);
      break;
    }

    default:
      return { ...base, valid: false, detail: `Unknown action: ${patch.action}`, diff: '', linesAdded: 0 };
  }

  // Final line-count safety
  const originalLines = content.split('\n').length;
  const newLines = newContent.split('\n').length;
  if (newLines < originalLines) {
    return { ...base, valid: false, detail: `File would shrink: ${originalLines} → ${newLines} lines`, diff: '', linesAdded: 0 };
  }

  const diff = generateDiff(content, newContent, patch.file);

  return { ...base, valid: true, detail: `+${newLines - originalLines} lines`, diff, linesAdded: newLines - originalLines };
}

// ─── Backup cleanup ─────────────────────────────────────────────────────────

async function cleanupBackups(filePath: string): Promise<void> {
  try {
    const dir = path.dirname(filePath);
    const base = path.basename(filePath);
    const entries = await fs.readdir(dir);
    const backups = entries
      .filter(e => e.startsWith(base + '.bak.'))
      .sort()
      .reverse(); // newest first
    // Remove all but the last MAX_BACKUPS_PER_FILE
    for (const old of backups.slice(MAX_BACKUPS_PER_FILE)) {
      try { await fs.unlink(path.join(dir, old)); } catch { /* ignore */ }
    }
  } catch { /* ignore if dir listing fails */ }
}

// ─── Patch application (with writes) ────────────────────────────────────────

async function applyPatch(patch: PatchOp): Promise<PatchResult> {
  const base = { file: patch.file, action: patch.action };

  const pathCheck = resolveAndValidate(patch.file);
  if (!pathCheck.valid) {
    return { ...base, success: false, detail: pathCheck.detail };
  }

  let content: string;
  try {
    content = await fs.readFile(pathCheck.fullPath, 'utf-8');
  } catch {
    return { ...base, success: false, detail: `File not found: ${patch.file}` };
  }

  const anchorIdx = content.indexOf(patch.anchor);
  if (anchorIdx === -1) {
    return { ...base, success: false, detail: `Anchor not found` };
  }
  // Anchor must be unique — prevent ambiguous writes
  if (content.indexOf(patch.anchor, anchorIdx + 1) !== -1) {
    return { ...base, success: false, detail: 'Ambiguous anchor (appears multiple times)' };
  }

  let newContent: string;

  switch (patch.action) {
    case 'insert': {
      if (content.includes(patch.content.trim())) {
        return { ...base, success: false, detail: 'Already present (duplicate)' };
      }
      const lineStart = content.lastIndexOf('\n', anchorIdx);
      const insertAt = lineStart === -1 ? 0 : lineStart + 1;
      newContent = content.slice(0, insertAt) + patch.content + '\n' + content.slice(insertAt);
      break;
    }

    case 'append': {
      if (content.includes(patch.content.trim())) {
        return { ...base, success: false, detail: 'Already present (duplicate)' };
      }
      const lineEnd = content.indexOf('\n', anchorIdx);
      const insertAt = lineEnd === -1 ? content.length : lineEnd + 1;
      newContent = content.slice(0, insertAt) + patch.content + '\n' + content.slice(insertAt);
      break;
    }

    case 'update': {
      if (!patch.oldValue) return { ...base, success: false, detail: 'Update requires oldValue' };
      const oldIdx = content.indexOf(patch.oldValue);
      if (oldIdx === -1) return { ...base, success: false, detail: 'Old value not found' };
      if (content.indexOf(patch.oldValue, oldIdx + 1) !== -1) return { ...base, success: false, detail: 'Old value ambiguous' };
      if (Math.abs(oldIdx - anchorIdx) > 2000) return { ...base, success: false, detail: 'Old value too far from anchor' };
      if (patch.content.length < patch.oldValue.length * 0.5) return { ...base, success: false, detail: 'Suspicious content shrink' };
      newContent = content.slice(0, oldIdx) + patch.content + content.slice(oldIdx + patch.oldValue.length);
      break;
    }

    default:
      return { ...base, success: false, detail: `Unknown action: ${patch.action}` };
  }

  // Final line-count safety
  const originalLines = content.split('\n').length;
  const newLines = newContent.split('\n').length;
  if (newLines < originalLines) {
    return { ...base, success: false, detail: `File would shrink: ${originalLines} → ${newLines}` };
  }

  // Backup original
  const backupPath = pathCheck.fullPath + '.bak.' + Date.now();
  await fs.copyFile(pathCheck.fullPath, backupPath);

  // Atomic write: tmp file + rename
  const tmpPath = pathCheck.fullPath + '.tmp.' + Date.now();
  await fs.writeFile(tmpPath, newContent, 'utf-8');
  await fs.rename(tmpPath, pathCheck.fullPath);

  // Clean up old backups — keep last MAX_BACKUPS_PER_FILE
  await cleanupBackups(pathCheck.fullPath);

  return { ...base, success: true, detail: `+${newLines - originalLines} lines` };
}

// ─── Revert from backup ──────────────────────────────────────────────────────

interface RevertFileResult {
  file: string;
  success: boolean;
  detail: string;
  backupTimestamp?: number;
}

/**
 * Find the most recent .bak file for a given source file.
 * Returns the full backup path and its timestamp, or null if none found.
 */
async function findNewestBackup(filePath: string): Promise<{ backupPath: string; timestamp: number } | null> {
  try {
    const dir = path.dirname(filePath);
    const base = path.basename(filePath);
    const entries = await fs.readdir(dir);
    const backups = entries
      .filter(e => e.startsWith(base + '.bak.'))
      .map(e => {
        const ts = parseInt(e.slice((base + '.bak.').length), 10);
        return { name: e, timestamp: ts };
      })
      .filter(b => !isNaN(b.timestamp))
      .sort((a, b) => b.timestamp - a.timestamp); // newest first

    if (backups.length === 0) return null;
    return { backupPath: path.join(dir, backups[0].name), timestamp: backups[0].timestamp };
  } catch {
    return null;
  }
}

/**
 * Revert all data files for a ticker to their most recent backups.
 * Only reverts files that have .bak files (i.e. files that were patched).
 *
 * dryRun=true: list which files would be reverted (no writes)
 * dryRun=false: restore from backups (atomic write)
 */
async function revertTicker(ticker: string, dryRun: boolean): Promise<{
  files: RevertFileResult[];
  revertedCount: number;
  skippedCount: number;
}> {
  const tickerLower = ticker.toLowerCase();
  const tickerDir = path.resolve(DATA_DIR, tickerLower);

  let entries: string[];
  try {
    entries = await fs.readdir(tickerDir);
  } catch {
    return { files: [], revertedCount: 0, skippedCount: 0 };
  }

  // Find all .ts source files that have backup files
  const tsFiles = entries.filter(e => e.endsWith('.ts') && !e.includes('.bak.'));
  const results: RevertFileResult[] = [];
  let revertedCount = 0;
  let skippedCount = 0;

  for (const tsFile of tsFiles) {
    const fullPath = path.resolve(tickerDir, tsFile);
    const relPath = `${tickerLower}/${tsFile}`;
    const backup = await findNewestBackup(fullPath);

    if (!backup) {
      // No backup = file was never patched, skip silently
      continue;
    }

    const backupAge = Date.now() - backup.timestamp;
    const backupAgeMinutes = Math.round(backupAge / 60000);

    if (dryRun) {
      results.push({
        file: relPath,
        success: true,
        detail: `Backup available (${backupAgeMinutes}m ago)`,
        backupTimestamp: backup.timestamp,
      });
      revertedCount++;
    } else {
      try {
        // Read backup content
        const backupContent = await fs.readFile(backup.backupPath, 'utf-8');
        const currentContent = await fs.readFile(fullPath, 'utf-8');

        // Skip if backup content is identical to current (already reverted)
        if (backupContent === currentContent) {
          results.push({ file: relPath, success: false, detail: 'Already matches backup (no change needed)' });
          skippedCount++;
          continue;
        }

        // Atomic write: tmp + rename
        const tmpPath = fullPath + '.tmp.' + Date.now();
        await fs.writeFile(tmpPath, backupContent, 'utf-8');
        await fs.rename(tmpPath, fullPath);

        results.push({
          file: relPath,
          success: true,
          detail: `Reverted from backup (${backupAgeMinutes}m ago)`,
          backupTimestamp: backup.timestamp,
        });
        revertedCount++;
      } catch (err) {
        results.push({
          file: relPath,
          success: false,
          detail: `Revert failed: ${err instanceof Error ? err.message : String(err)}`,
        });
        skippedCount++;
      }
    }
  }

  return { files: results, revertedCount, skippedCount };
}

// ─── Route handler ──────────────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  const gateError = checkAiGate(request);
  if (gateError) return gateError;

  try {
    const body = await request.json() as {
      ticker: string;
      agentId?: string;
      analysis?: string;
      dryRun?: boolean;
      revert?: boolean;
      patches?: PatchOp[];
    };

    const { ticker, dryRun = true } = body;

    if (!ticker) {
      return NextResponse.json({ error: 'Missing ticker' }, { status: 400 });
    }

    // Strict ticker validation — prevent path traversal and directory listing abuse
    if (!TICKER_PATTERN.test(ticker.toLowerCase())) {
      return NextResponse.json({ error: 'Invalid ticker format' }, { status: 400 });
    }

    // ── REVERT MODE: restore files from .bak backups ──
    if (body.revert) {
      const result = await revertTicker(ticker, dryRun);

      if (result.files.length === 0) {
        return NextResponse.json({
          revert: true,
          dryRun,
          error: `No backup files found for ${ticker.toUpperCase()}. Nothing to revert.`,
        }, { status: 404 });
      }

      // Auto re-seed DB after successful revert (same as apply mode)
      let reseed: { triggered: boolean; success?: boolean; message?: string } = { triggered: false };
      if (!dryRun && result.revertedCount > 0) {
        try {
          const origin = new URL(request.url).origin;
          const reseedRes = await fetch(`${origin}/api/db/setup`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
          });
          if (reseedRes.ok) {
            const reseedData = await reseedRes.json();
            reseed = { triggered: true, success: true, message: reseedData.message };
            console.log(`[apply/revert] Auto re-seeded database after revert: ${reseedData.message}`);
          } else {
            reseed = { triggered: true, success: false, message: `HTTP ${reseedRes.status}` };
          }
        } catch (e) {
          reseed = { triggered: true, success: false, message: (e as Error).message };
        }
      }

      return NextResponse.json({
        revert: true,
        dryRun,
        ticker: ticker.toUpperCase(),
        files: result.files,
        revertedCount: result.revertedCount,
        skippedCount: result.skippedCount,
        ...(dryRun ? {} : { reseed }),
        summary: dryRun
          ? `${result.revertedCount} file(s) can be reverted for ${ticker.toUpperCase()}`
          : `Reverted ${result.revertedCount} file(s) for ${ticker.toUpperCase()}${result.skippedCount > 0 ? ` (${result.skippedCount} skipped)` : ''}`,
      });
    }

    const agentId = body.agentId || '';
    let patches: PatchOp[];

    if (dryRun) {
      // ── VALIDATE-ONLY MODE: pre-extracted patches from Decision Dashboard ──
      if (body.patches && Array.isArray(body.patches) && body.patches.length > 0) {
        patches = body.patches as PatchOp[];

        if (patches.length > MAX_PATCH_COUNT) {
          patches = patches.slice(0, MAX_PATCH_COUNT);
        }

        // Auto-generate missing cross-ref patches
        const crossRefResult = await ensureCrossRefPatches(patches, ticker);
        patches = crossRefResult.patches;
        const crossRefsAutoGenerated = crossRefResult.autoGenerated;

        if (patches.length > MAX_PATCH_COUNT) {
          patches = patches.slice(0, MAX_PATCH_COUNT);
        }

        // Validate each patch and generate diffs (NO writes)
        const autoGenStartIdx = patches.length - crossRefsAutoGenerated;
        const previews: PatchPreviewItem[] = [];
        for (let pi = 0; pi < patches.length; pi++) {
          const preview = await validatePatch(patches[pi]);
          if (pi >= autoGenStartIdx) {
            preview.autoGenerated = true;
            if (preview.detail && !preview.detail.includes('auto-generated')) {
              preview.detail = `[auto-generated cross-ref] ${preview.detail}`;
            }
          }
          previews.push(preview);
        }

        const validCount = previews.filter(p => p.valid).length;
        const invalidCount = previews.filter(p => !p.valid).length;
        const totalLinesAdded = previews.reduce((sum, p) => sum + p.linesAdded, 0);
        const filesAffected = new Set(previews.filter(p => p.valid).map(p => p.file)).size;

        return NextResponse.json({
          dryRun: true,
          patchCount: patches.length,
          validCount,
          invalidCount,
          totalLinesAdded,
          filesAffected,
          crossRefsAutoGenerated,
          previews,
          patches: patches.filter((_, i) => previews[i].valid),
          summary: `${validCount} valid patches across ${filesAffected} files (+${totalLinesAdded} lines)${invalidCount > 0 ? ` — ${invalidCount} rejected` : ''}${crossRefsAutoGenerated > 0 ? ` (${crossRefsAutoGenerated} cross-ref auto-generated)` : ''}`,
        });
      }

      // ── PREVIEW MODE: extract patches from analysis via AI ──
      const ANTHROPIC_API_KEY = (process.env as Record<string, string | undefined>)['ANTHROPIC_API_KEY'] || '';
      if (!ANTHROPIC_API_KEY) {
        return NextResponse.json({ error: 'ANTHROPIC_API_KEY not configured' }, { status: 500 });
      }

      const analysis = (body.analysis || '').slice(0, MAX_ANALYSIS_LENGTH);
      if (!analysis) {
        return NextResponse.json({ error: 'Missing analysis for preview' }, { status: 400 });
      }

      // ── Adaptive file context: target files get more context ──
      const tickerLower = ticker.toLowerCase();
      const tickerDir = path.resolve(DATA_DIR, tickerLower);
      const analysisLower = analysis.toLowerCase();

      // Keywords to detect likely target files from the analysis text
      const TARGET_KEYWORDS: Record<string, string[]> = {
        'timeline.ts': ['timeline', 'event', 'holdings update', 'changes[', 'details['],
        'sec-filings.ts': ['sec filing', 'sec-filing', '8-k', '10-q', '10-k', '424b', 'form 4', 'sc 13', 'cross-ref', 'cross_ref'],
        'capital.ts': ['capital', 'shares', 'offering', 'equity', 'shareholder', 'dilut'],
        'financials.ts': ['financial', 'quarterly', 'revenue', 'cash', 'debt', 'opex', 'balance sheet'],
        'quarterly-metrics.ts': ['quarterly', 'metrics', 'eth holdings', 'staking'],
        'catalysts.ts': ['catalyst', 'milestone', 'upcoming'],
        'company.ts': ['company', 'defaults', 'current price', 'stock price', 'eth price'],
        'ethereum-adoption.ts': ['ethereum adoption', 'eth ecosystem', 'rwa', 'tokeniz'],
      };

      const HEAD_TARGET = 3000;  // chars for likely target files
      const HEAD_OTHER = 800;    // chars for non-target files

      let fileManifest = '';
      let availableFiles: string[] = [];
      try {
        const entries = await fs.readdir(tickerDir);
        const tsFiles = entries.filter(f => f.endsWith('.ts')).sort();
        availableFiles = tsFiles.map(f => `${tickerLower}/${f}`);
        const manifests: string[] = [];
        for (const f of tsFiles) {
          const rel = `${tickerLower}/${f}`;
          const fullPath = path.resolve(tickerDir, f);
          const content = await fs.readFile(fullPath, 'utf-8');

          // Check if this file is a likely target based on analysis keywords
          const keywords = TARGET_KEYWORDS[f] || [];
          const isTarget = keywords.some(kw => analysisLower.includes(kw));
          const headLen = isTarget ? HEAD_TARGET : HEAD_OTHER;
          const head = content.slice(0, headLen).replace(/\n/g, '\\n');
          manifests.push(`- ${rel}${isTarget ? ' [TARGET]' : ''}\n  HEAD: ${head}`);
        }
        fileManifest = manifests.join('\n');
      } catch {
        fileManifest = `(could not list files for ${tickerLower}/)`;
      }

      // ── Schema + filing template context ──
      const schemaContext = renderSchemaContext(tickerLower, availableFiles);
      const detectedFilingType = analysisLower.match(
        /\b(8-K|10-[QK]|424B[457]|SC\s*13[GD]|Form\s*4|S-[38]|S-3ASR|DEF\s*14A|DEFA14A|DEFR14A|FWP)\b/i
      )?.[1] || null;
      const templateContext = renderFilingTemplateContext(tickerLower, detectedFilingType);

      // ── Build extraction prompt with schema injection ──
      let extractionPrompt = `You are a database patch generator for the ABISON investment research platform. Given an agent analysis output, extract ONLY the concrete database changes proposed.

TICKER: ${ticker.toUpperCase()}
AGENT: ${agentId}

AVAILABLE FILES (use ONLY these exact paths):
${fileManifest}
`;

      if (schemaContext) {
        extractionPrompt += `
DATA SCHEMAS — your patches MUST match these field structures exactly:
${schemaContext}
`;
      }

      if (templateContext) {
        extractionPrompt += `
FILING TYPE TEMPLATE — example entries for this filing type:
${templateContext}
`;
      }

      extractionPrompt += `
Output ONLY valid JSON — an array of patch operations. No markdown, no explanation.

Each patch object:
{
  "file": "string — relative path from src/data/ — MUST be one of the files listed above",
  "action": "insert | append | update",
  "anchor": "string — unique text in the target file to locate the insertion point (must appear EXACTLY ONCE)",
  "content": "string — the TypeScript code to insert/append (must NOT contain import/require/exec/eval)",
  "oldValue": "string — ONLY for 'update' action, the exact text being replaced (must appear EXACTLY ONCE in file)"
}

Rules:
- CRITICAL: the "file" field must EXACTLY match one of the AVAILABLE FILES above. Do NOT guess or abbreviate file names.
- CRITICAL: your "content" field MUST use the exact field names, types, and formatting shown in DATA SCHEMAS above. Do NOT invent fields or change casing.
- action=insert: Insert BEFORE anchor (for adding new entries at top of reverse-chronological lists)
- action=append: Insert AFTER anchor (for adding bullets/fields to existing entries)
- action=update: Replace oldValue with content (oldValue must be UNIQUE in the file — use enough surrounding context)
- anchor must appear EXACTLY ONCE in the target file — include enough context for uniqueness
- NEVER produce patches that delete content or shrink data
- content must be valid TypeScript matching the file's style
- If the analysis says "Skip" or "Already Incorporated", produce NO patch
- If no patches are needed, return: []
- MANDATORY: When inserting a new entry into sec-filings.ts, you MUST ALSO insert a FILING_CROSS_REFS entry with key "FORM_TYPE|YYYY-MM-DD" (using the filing date in ISO format). Include one { source, data } entry for EACH data file you are patching. Use the FILING_CROSS_REFS export declaration line as anchor with action=append.

ANALYSIS TO EXTRACT FROM:
${analysis}`;

      // ── Token budget guard: progressive truncation if prompt too large ──
      const MAX_PROMPT_CHARS = 120000; // ~30K tokens
      if (extractionPrompt.length > MAX_PROMPT_CHARS) {
        // Step 1: Rebuild manifest with non-target files at 400 chars
        try {
          const entries = await fs.readdir(tickerDir);
          const tsFiles = entries.filter(f => f.endsWith('.ts')).sort();
          const manifests: string[] = [];
          for (const f of tsFiles) {
            const rel = `${tickerLower}/${f}`;
            const fullPath = path.resolve(tickerDir, f);
            const content = await fs.readFile(fullPath, 'utf-8');
            const keywords = TARGET_KEYWORDS[f] || [];
            const isTarget = keywords.some(kw => analysisLower.includes(kw));
            const headLen = isTarget ? HEAD_TARGET : 400;
            const head = content.slice(0, headLen).replace(/\n/g, '\\n');
            manifests.push(`- ${rel}${isTarget ? ' [TARGET]' : ''}\n  HEAD: ${head}`);
          }
          fileManifest = manifests.join('\n');
          // Rebuild prompt with trimmed manifest
          extractionPrompt = extractionPrompt.replace(
            /AVAILABLE FILES \(use ONLY these exact paths\):\n[\s\S]*?\n\n/,
            `AVAILABLE FILES (use ONLY these exact paths):\n${fileManifest}\n\n`
          );
        } catch { /* keep existing prompt */ }
      }

      // Step 2: If still too large, truncate analysis from the tail
      if (extractionPrompt.length > MAX_PROMPT_CHARS) {
        const overflow = extractionPrompt.length - MAX_PROMPT_CHARS + 200;
        const truncatedAnalysis = analysis.slice(0, analysis.length - overflow) + '\n\n[... analysis truncated for token budget ...]';
        extractionPrompt = extractionPrompt.replace(
          /ANALYSIS TO EXTRACT FROM:\n[\s\S]*$/,
          `ANALYSIS TO EXTRACT FROM:\n${truncatedAnalysis}`
        );
      }

      const claudeRes = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': ANTHROPIC_API_KEY,
          'anthropic-version': '2023-06-01',
        },
        body: JSON.stringify({
          model: 'claude-sonnet-4-5-20250929',
          max_tokens: 8192,
          messages: [{ role: 'user', content: extractionPrompt }],
        }),
      });

      if (!claudeRes.ok) {
        const errText = await claudeRes.text();
        console.error('[apply] Claude API error:', errText);
        return NextResponse.json({ error: 'AI patch extraction failed' }, { status: 502 });
      }

      const claudeData = await claudeRes.json() as {
        content: Array<{ type: string; text?: string }>;
      };
      const responseText = claudeData.content
        .filter((b) => b.type === 'text')
        .map((b) => b.text)
        .join('');

      try {
        const jsonStr = responseText.replace(/^```json?\n?/, '').replace(/\n?```$/, '').trim();
        patches = JSON.parse(jsonStr);
      } catch {
        console.error('[apply] Failed to parse patches:', responseText.slice(0, 500));
        return NextResponse.json({
          error: 'Failed to parse structured patches from AI',
          rawResponse: responseText.slice(0, 200),
        }, { status: 422 });
      }

      if (!Array.isArray(patches)) {
        return NextResponse.json({ error: 'Expected array of patches' }, { status: 422 });
      }

      // Cap patch count to prevent AI generating excessive changes
      if (patches.length > MAX_PATCH_COUNT) {
        patches = patches.slice(0, MAX_PATCH_COUNT);
      }

      if (patches.length === 0) {
        return NextResponse.json({
          dryRun: true,
          patchCount: 0,
          previews: [],
          patches: [],
          summary: 'No database changes needed — all items already incorporated or skipped.',
        });
      }

      // ── Auto-generate missing cross-ref patches ──
      const crossRefResult = await ensureCrossRefPatches(patches, ticker);
      patches = crossRefResult.patches;
      const crossRefsAutoGenerated = crossRefResult.autoGenerated;
      if (crossRefsAutoGenerated > 0) {
        console.log(`[apply] Auto-generated ${crossRefsAutoGenerated} cross-ref patch(es) for ${ticker.toUpperCase()}`);
      }

      // Re-cap after auto-generation
      if (patches.length > MAX_PATCH_COUNT) {
        patches = patches.slice(0, MAX_PATCH_COUNT);
      }

      // Validate each patch and generate diffs (NO writes)
      // Mark auto-generated patches so the UI can flag them
      const autoGenStartIdx = patches.length - crossRefsAutoGenerated;
      const previews: PatchPreviewItem[] = [];
      for (let pi = 0; pi < patches.length; pi++) {
        const preview = await validatePatch(patches[pi]);
        if (pi >= autoGenStartIdx) {
          preview.autoGenerated = true;
          if (preview.detail && !preview.detail.includes('auto-generated')) {
            preview.detail = `[auto-generated cross-ref] ${preview.detail}`;
          }
        }
        previews.push(preview);
      }

      const validCount = previews.filter(p => p.valid).length;
      const invalidCount = previews.filter(p => !p.valid).length;
      const totalLinesAdded = previews.reduce((sum, p) => sum + p.linesAdded, 0);
      const filesAffected = new Set(previews.filter(p => p.valid).map(p => p.file)).size;

      return NextResponse.json({
        dryRun: true,
        patchCount: patches.length,
        validCount,
        invalidCount,
        totalLinesAdded,
        filesAffected,
        crossRefsAutoGenerated,
        previews,
        patches: patches.filter((_, i) => previews[i].valid), // Only return valid patches for confirm step
        summary: `${validCount} valid patches across ${filesAffected} files (+${totalLinesAdded} lines)${invalidCount > 0 ? ` — ${invalidCount} rejected` : ''}${crossRefsAutoGenerated > 0 ? ` (${crossRefsAutoGenerated} cross-ref auto-generated)` : ''}`,
      });

    } else {
      // ── APPLY MODE: apply pre-validated patches ──
      patches = body.patches || [];

      if (patches.length === 0) {
        return NextResponse.json({ error: 'No patches to apply' }, { status: 400 });
      }

      if (patches.length > MAX_PATCH_COUNT) {
        return NextResponse.json({ error: `Too many patches: ${patches.length} (max ${MAX_PATCH_COUNT})` }, { status: 400 });
      }

      // Re-validate and apply each patch
      const results: PatchResult[] = [];
      for (const patch of patches) {
        // Content safety checks (re-check even though preview validated)
        if (DANGEROUS_PATTERN.test(patch.content)) {
          results.push({ file: patch.file, action: patch.action, success: false, detail: 'Blocked: dangerous code pattern' });
          continue;
        }
        if (patch.content.length > MAX_PATCH_CONTENT_LENGTH) {
          results.push({ file: patch.file, action: patch.action, success: false, detail: 'Content too large' });
          continue;
        }
        results.push(await applyPatch(patch));
      }

      const successCount = results.filter(r => r.success).length;
      const failCount = results.filter(r => !r.success).length;

      // Auto re-seed the Postgres database so check-analyzed reflects newly written data.
      // The workflow writes to .ts source files, but check-analyzed queries Postgres.
      // Without this step, articles remain UNTRACKED until a manual db/setup is run.
      let reseed: { triggered: boolean; success?: boolean; message?: string } = { triggered: false };
      if (successCount > 0) {
        try {
          const origin = new URL(request.url).origin;
          const reseedRes = await fetch(`${origin}/api/db/setup`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
          });
          if (reseedRes.ok) {
            const reseedData = await reseedRes.json();
            reseed = { triggered: true, success: true, message: reseedData.message };
            console.log(`[apply] Auto re-seeded database after patches: ${reseedData.message}`);
          } else {
            const errText = await reseedRes.text();
            reseed = { triggered: true, success: false, message: `HTTP ${reseedRes.status}` };
            console.error(`[apply] Database re-seed failed: ${reseedRes.status} — ${errText.slice(0, 200)}`);
          }
        } catch (e) {
          reseed = { triggered: true, success: false, message: (e as Error).message };
          console.error('[apply] Database re-seed error:', e);
        }
      }

      return NextResponse.json({
        dryRun: false,
        patchCount: patches.length,
        applied: successCount,
        failed: failCount,
        results,
        reseed,
        summary: failCount === 0
          ? `Applied ${successCount} patches to ${ticker.toUpperCase()} database`
          : `Applied ${successCount}/${patches.length} patches (${failCount} failed)`,
      });
    }
  } catch (error) {
    console.error('[apply] Error:', error);
    return NextResponse.json(
      { error: `Apply failed: ${error instanceof Error ? error.message : String(error)}` },
      { status: 500 }
    );
  }
}
